apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-project-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: cloud-project.info
      http:
        paths:
          - path: /housing-publication/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: housing-publication
                port:
                  number: 8080
          - path: /user-management/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-management
                port:
                  number: 8080
