apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: housing-publication
    version: "1.0"
  name: housing-publication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housing-publication
  strategy: {}
  template:
    metadata:
      labels:
        app: housing-publication
    spec:
      containers:
        - name: housing-publication
          image: cloudprojectantoninkylian/housing-publication:1.0.0
          imagePullPolicy: IfNotPresent
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-management
    version: "1.0"
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  strategy: {}
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: cloudprojectantoninkylian/user-management:1.0.0
          imagePullPolicy: IfNotPresent
          env : 
            - name : SPRING_DATASOURCE_URL
              value : jdbc:postgresql://postgres:5432/postgresdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: housing-publicaion
  name: housing-publication
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: housing-publication
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-management
  name: user-management
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: user-management
  type: ClusterIP
